spring.application.name=timetable-generator

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=japanese

spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.jwtSecret = fb627cd330771e6cf1d13ca64592f2ca
# 24 ????
app.jwtExpirationMs=86400000
# 7 ????
app.jwtRefreshExpirationMs=604800000

#logging.level.com.example.timetablegenerator=DEBUG
#logging.level.org.springframework.security=DEBUG