-- =========================================================
-- FACULTIES
-- =========================================================
INSERT INTO faculties (name) VALUES
                                 ('Faculty of Engineering and Informatics'),
                                 ('Faculty of Economics and Management'),
                                 ('Faculty of Social Sciences'),
                                 ('Medical Faculty'),
                                 ('Faculty of Humanities');

-- =========================================================
-- DEPARTMENTS
-- =========================================================
INSERT INTO departments (name, faculty_id) VALUES
                                               ('Department of Computer Science', 1),
                                               ('Department of Applied Mathematics and Informatics', 1),
                                               ('Programs of Industrial and Electronic Engineering', 1),
                                               ('Department of Economics', 2),
                                               ('Department of Management', 2),
                                               ('Department of International and Business Law', 2),
                                               ('Department of Social Sciences', 3),
                                               ('Department of Medical Faculty', 4),
                                               ('Department of Humanities', 5);

-- =========================================================
-- MAJORS
-- =========================================================
INSERT INTO majors (name, short_name, degree, department_id) VALUES
                                                                 ('Computer Science', 'COM', 'BACHELOR', 1),
                                                                 ('COMSE', 'COMSE', 'BACHELOR', 1),
                                                                 ('COMCEH', 'COMCEH', 'BACHELOR', 1),
                                                                 ('COMFCI', 'COMFCI', 'BACHELOR', 1),
                                                                 ('Applied Mathematics and Informatics', 'MATH', 'BACHELOR', 2),
                                                                 ('MATDAIS', 'MATDAIS', 'BACHELOR', 2),
                                                                 ('MATMIE', 'MATMIE', 'BACHELOR', 2),
                                                                 ('EEAIR', 'EEAIR', 'BACHELOR', 3),
                                                                 ('IEMIT', 'IEMIT', 'BACHELOR', 3),
                                                                 ('International Economics and Business', 'IBE', 'BACHELOR', 4),
                                                                 ('International Finance and Auditing', 'IFA', 'BACHELOR', 4),
                                                                 ('Environmental Economics', 'ENV', 'BACHELOR', 4),
                                                                 ('Economics', 'ECO-M', 'MASTER', 4),
                                                                 ('Management', 'MNG', 'BACHELOR', 5),
                                                                 ('Tourism Management', 'TM', 'BACHELOR', 5),
                                                                 ('Management', 'MNG-M', 'MASTER', 5),
                                                                 ('International and Business Law', 'LAW', 'BACHELOR', 6),
                                                                 ('International and Business Law', 'LAW-M', 'MASTER', 6),
                                                                 ('International Relations', 'INT', 'BACHELOR', 7),
                                                                 ('Psychology', 'PS', 'BACHELOR', 7),
                                                                 ('Journalism', 'JRN', 'BACHELOR', 7),
                                                                 ('Advertising and Public Relations', 'ADV', 'BACHELOR', 7),
                                                                 ('International Relations', 'INT-M', 'MASTER', 7),
                                                                 ('Psychology', 'PS-M', 'MASTER', 7),
                                                                 ('Journalism', 'JRN-M', 'MASTER', 7),
                                                                 ('Advertising and Public Relations', 'ADV-M', 'MASTER', 7),
                                                                 ('General Medicine', 'MGN', 'SPECIALIST', 8),
                                                                 ('Linguistics', 'LIN', 'BACHELOR', 9),
                                                                 ('Philology', 'PHIL', 'BACHELOR', 9),
                                                                 ('Education', 'PED', 'BACHELOR', 9),
                                                                 ('Linguistics', 'LIN-M', 'MASTER', 9),
                                                                 ('Philology', 'PHIL-M', 'MASTER', 9),
                                                                 ('Education', 'PED-M', 'MASTER', 9);

-- =========================================================
-- STUDY GROUPS
-- =========================================================
INSERT INTO study_groups (name, major_id, course, student_count) VALUES
                                                                     ('COMSE-25', 2, 1, 25),
                                                                     ('COMCEH-25', 3, 1, 25),
                                                                     ('COMFCI-25', 4, 1, 25),
                                                                     ('COMCEH-24', 3, 2, 25),
                                                                     ('COMSE-24', 2, 2, 25),
                                                                     ('COMFCI-24', 4, 2, 25),
                                                                     ('COMCEH-23', 3, 3, 25),
                                                                     ('COMSE-23/  1-Group', 2, 3, 20),
                                                                     ('COMSE-23/  2-Group', 2, 3, 20),
                                                                     ('COMFCI-23', 4, 3, 25),
                                                                     ('COM-22 /  1-Group', 1, 4, 20),
                                                                     ('COM-22 /  2-Group', 1, 4, 20),
                                                                     ('MATDAIS-25', 6, 1, 25),
                                                                     ('MATMIE-25', 7, 1, 25),
                                                                     ('MATDAIS-24', 6, 2, 25),
                                                                     ('MATMIE-24', 7, 2, 25),
                                                                     ('MATDAIS-23', 6, 3, 25),
                                                                     ('MATMIE-23', 7, 3, 25),
                                                                     ('MATH-22', 5, 4, 25),
                                                                     ('EEAIR-25', 8, 1, 25),
                                                                     ('IEMIT-25', 9, 1, 25),
                                                                     ('EEAIR-24', 8, 2, 25),
                                                                     ('IEMIT-24', 9, 2, 25),
                                                                     ('EEAIR-23', 8, 3, 25),
                                                                     ('IEMIT-23', 9, 3, 25);

-- =========================================================
-- TEACHERS
-- =========================================================
INSERT INTO teachers (full_name) VALUES
                                     ('Dr. Aslan Al Khan'),
                                     ('Dr. Musa Abdujabbarov'),
                                     ('Dr. Mekia Gaso'),
                                     ('Mr. Dim Shaiakhmetov'),
                                     ('Dr. Ahmad Sarosh'),
                                     ('Dr. Ruslan Isaev'),
                                     ('Dr. Tauheed Khan'),
                                     ('Cholponbek Esenbekov'),
                                     ('Dr. Remudin Mekuria'),
                                     ('Mr. Tursunali Baimuradov'),
                                     ('Ms. Siren Kerimbaeva'),
                                     ('Dr. Sherali Matanov'),
                                     ('Mr. Samat Elikbaev'),
                                     ('Ms. Tattybubu Arap kyzy'),
                                     ('Ms. Meerim'),
                                     ('Dr. Burul Shambetova'),
                                     ('Mr. Murrey Eldred'),
                                     ('Ms. Ainuuru Zhoolchieva'),
                                     ('Ms. Imtiyaz gulbarga');

-- =========================================================
-- ROOMS
-- =========================================================
INSERT INTO rooms (name, capacity, type) VALUES
                                             ('B101', 30, 'CLASSROOM'),
                                             ('B102', 30, 'CLASSROOM'),
                                             ('B103', 30, 'CLASSROOM'),
                                             ('B104', 30, 'CLASSROOM'),
                                             ('B105', 30, 'CLASSROOM'),
                                             ('B106', 30, 'CLASSROOM'),
                                             ('B109 (APPLE LAB)', 24, 'COMPUTER_LAB'),
                                             ('B110 LAB', 24, 'COMPUTER_LAB'),
                                             ('B111 LAB', 24, 'COMPUTER_LAB'),
                                             ('B113', 30, 'CLASSROOM'),
                                             ('B201', 30, 'CLASSROOM'),
                                             ('B202', 30, 'CLASSROOM'),
                                             ('B203', 30, 'CLASSROOM'),
                                             ('B204', 30, 'CLASSROOM'),
                                             ('B205', 30, 'CLASSROOM'),
                                             ('BIGLAB', 40, 'COMPUTER_LAB'),
                                             ('LAB3(210)', 24, 'COMPUTER_LAB'),
                                             ('LAB4(211)', 24, 'COMPUTER_LAB'),
                                             ('LAB5(213)', 24, 'COMPUTER_LAB');

-- =========================================================
-- SUBJECTS
-- =========================================================
INSERT INTO subjects (name, code, total_hours, hours_per_week, major_id) VALUES
                                                                             ('Introduction to Engineering and Computer Science', 'COM 100', 6, 6, 1),
                                                                             ('Engineering Computer Graphics', 'COM 108', 4, 4, 1),
                                                                             ('English Language', 'COM 109', 4, 4, 1),
                                                                             ('Programming Languages I', 'COM 113', 6, 6, 1),
                                                                             ('Calculus I', 'MAT 601', 6, 6, 5),
                                                                             ('Algebra and Geometry I', 'MAT 607', 4, 4, 5),
                                                                             ('Physical Education I', 'MDE 131', 1, 1, 1),
                                                                             ('Russian Language', 'MDE 133', 2, 2, 1),
                                                                             ('Programming Language II', 'COM 102', 6, 6, 1),
                                                                             ('Philosophy of Technologies', 'COM 410', 4, 4, 1),
                                                                             ('Discrete Mathematics I', 'MAT 151', 6, 6, 5),
                                                                             ('Calculus II', 'MAT 602', 6, 6, 5),
                                                                             ('Russian Language II', 'MDE 112', 2, 2, 1),
                                                                             ('Physical Education II', 'MDE 136', 1, 1, 1),
                                                                             ('German', 'MDE 154', 4, 4, 1),
                                                                             ('Manas Studies', 'MDE 404', 2, 2, 1),
                                                                             ('Web Technologies', 'COM 203', 6, 6, 1),
                                                                             ('Database Systems', 'COM 205', 6, 6, 1),
                                                                             ('Object Oriented Programming (OOP)', 'COM 235', 6, 6, 1),
                                                                             ('Computational Mathematics', 'MAT 231', 4, 4, 5),
                                                                             ('Statistics with Python', 'MAT 389', 4, 4, 5),
                                                                             ('Kyrgyz Language and Literature I', 'MDE 201', 4, 4, 1),
                                                                             ('Physical Education III', 'MDE 227', 1, 1, 1),
                                                                             ('Web Programming', 'COM 204', 6, 6, 1),
                                                                             ('Electronics', 'COM 224', 4, 4, 1),
                                                                             ('Design and Analysis of algorithms', 'COM 366', 6, 6, 1),
                                                                             ('Robotics', 'COM 419', 4, 4, 1),
                                                                             ('Kyrgyz Language and Literature IV', 'MDE 202', 4, 4, 1),
                                                                             ('History of Kyrgyzstan', 'MDE 208', 4, 4, 1),
                                                                             ('Geography of Kyrgyzstan', 'MDE 216', 2, 2, 1),
                                                                             ('Physical Education IV', 'MDE 220', 1, 1, 1),
                                                                             ('Educational Interrnship', 'COM 055', 6, 6, 1),
                                                                             ('Computer Networks and Telecommunication', 'COM 352', 6, 6, 1),
                                                                             ('Software Engineering', 'COM 353', 6, 6, 1),
                                                                             ('Computer architecture and operating systems', 'COM 367', 6, 6, 1),
                                                                             ('Probability and Statistics', 'COM 535', 6, 6, 1),
                                                                             ('Artificial Intelligence', 'COM 302', 6, 6, 1),
                                                                             ('Industrial Project Internship', 'COM 328', 6, 6, 1),
                                                                             ('Mobile Development', 'COM 363', 6, 6, 1),
                                                                             ('Information Security', 'COM 412', 6, 6, 1),
                                                                             ('Machine Learning', 'COM 416', 6, 6, 1),
                                                                             ('Pre-qualification internship', 'COM 048', 12, 12, 1),
                                                                             ('Basics of science research', 'COM 470', 6, 6, 1),
                                                                             ('Data mining and storage', 'COM 476', 6, 6, 1),
                                                                             ('Engineering Economics', 'IND 100', 6, 6, 9),
                                                                             ('Cloud Computing', 'COM 344', 6, 6, 1),
                                                                             ('Image Processing for Computer Vision', 'COM 482', 6, 6, 1),
                                                                             ('SDAT(Software Development Automation Testing)', 'COM 486', 6, 6, 1),
                                                                             ('Final State Certification', 'COM 910', 6, 6, 1);

-- =========================================================
-- SUBJECT <-> TEACHER
-- =========================================================
INSERT INTO subject_teachers (subject_id, teacher_id) VALUES
                                                          (1, 1), (1, 2),
                                                          (2, 4),
                                                          (3, 15),
                                                          (4, 2), (4, 7),
                                                          (5, 12),
                                                          (6, 12),
                                                          (7, 17),
                                                          (8, 14),

                                                          (9, 2), (9, 7),
                                                          (10, 1),
                                                          (11, 12),
                                                          (12, 12),
                                                          (13, 14),
                                                          (14, 17),
                                                          (15, 15),
                                                          (16, 14),

                                                          (17, 4),
                                                          (18, 6),
                                                          (19, 2), (19, 4),
                                                          (20, 12),
                                                          (21, 18),
                                                          (22, 14),
                                                          (23, 17),

                                                          (24, 4),
                                                          (25, 3),
                                                          (26, 7),
                                                          (27, 5),
                                                          (28, 14),
                                                          (29, 14),
                                                          (30, 14),
                                                          (31, 17),

                                                          (32, 10),
                                                          (33, 6),
                                                          (34, 9),
                                                          (35, 8),
                                                          (36, 18),

                                                          (37, 5),
                                                          (38, 10),
                                                          (39, 19),
                                                          (40, 16),
                                                          (41, 5),

                                                          (42, 10),
                                                          (43, 1),
                                                          (44, 18),
                                                          (45, 13),

                                                          (46, 9),
                                                          (47, 3),
                                                          (48, 11),
                                                          (49, 12);

-- =========================================================
-- SUBJECT <-> GROUP
-- =========================================================
INSERT INTO subject_groups (subject_id, group_id) VALUES
-- 1 курс COM / MAT
(1, 1), (1, 2), (1, 3),
(2, 1), (2, 2), (2, 3),
(3, 1), (3, 2), (3, 3),
(4, 1), (4, 2), (4, 3),
(5, 13), (5, 14),
(6, 13), (6, 14),
(7, 1), (7, 2), (7, 3),
(8, 1), (8, 2), (8, 3),

-- 2 курс
(9, 4), (9, 5), (9, 6),
(10, 4), (10, 5), (10, 6),
(11, 15), (11, 16),
(12, 15), (12, 16),
(13, 4), (13, 5), (13, 6),
(14, 4), (14, 5), (14, 6),
(15, 4), (15, 5), (15, 6),
(16, 4), (16, 5), (16, 6),

-- 3 курс
(17, 7), (17, 8), (17, 9), (17, 10),
(18, 7), (18, 8), (18, 9), (18, 10),
(19, 7), (19, 8), (19, 9), (19, 10),
(20, 17), (20, 18),
(21, 17), (21, 18),
(22, 7), (22, 8), (22, 9), (22, 10),
(23, 7), (23, 8), (23, 9), (23, 10),

(24, 7), (24, 8), (24, 9), (24, 10),
(25, 7), (25, 8), (25, 9), (25, 10),
(26, 7), (26, 8), (26, 9), (26, 10),
(27, 7), (27, 8), (27, 9), (27, 10),
(28, 7), (28, 8), (28, 9), (28, 10),
(29, 7), (29, 8), (29, 9), (29, 10),
(30, 7), (30, 8), (30, 9), (30, 10),
(31, 7), (31, 8), (31, 9), (31, 10),

-- 4 курс
(32, 11), (32, 12),
(33, 11), (33, 12),
(34, 11), (34, 12),
(35, 11), (35, 12),
(36, 11), (36, 12),
(37, 11), (37, 12),
(38, 11), (38, 12),
(39, 11), (39, 12),
(40, 11), (40, 12),
(41, 11), (41, 12),
(42, 11), (42, 12),
(43, 11), (43, 12),
(44, 11), (44, 12),
(45, 25),
(46, 11), (46, 12),
(47, 11), (47, 12),
(48, 11), (48, 12),
(49, 11), (49, 12);

-- =========================================================
-- TIMETABLES
-- =========================================================
INSERT INTO timetables (name, academic_year_start, academic_year_end, semester, version, created_at, status, generation_settings, conflict_report) VALUES
                                                                                                                                                       ('Course Schedule FALL 2025-2026 v0', 2025, 2026, 'FALL', 0, NOW(), 'DRAFT', NULL, NULL),
                                                                                                                                                       ('Course Schedule SPRING 2025-2026 v0', 2025, 2026, 'SPRING', 0, NOW(), 'DRAFT', NULL, NULL);

-- =========================================================
-- TIME SLOTS
-- =========================================================
INSERT INTO time_slots (day_of_week, slot_order, start_time, end_time, description) VALUES
                                                                                        (NULL, 1,  '08:00:00', '08:40:00', '1st lesson'),
                                                                                        (NULL, 2,  '08:45:00', '09:25:00', '2nd lesson'),
                                                                                        (NULL, 3,  '09:30:00', '10:10:00', '3rd lesson'),
                                                                                        (NULL, 4,  '10:15:00', '10:55:00', '4th lesson'),
                                                                                        (NULL, 5,  '11:00:00', '11:40:00', '5th lesson'),
                                                                                        (NULL, 6,  '11:45:00', '12:25:00', '6th lesson'),
                                                                                        (NULL, 7,  '12:30:00', '13:10:00', '7th lesson'),
                                                                                        (NULL, 8,  '13:15:00', '13:55:00', '8th lesson'),
                                                                                        (NULL, 9,  '14:00:00', '14:40:00', '9th lesson'),
                                                                                        (NULL, 10, '14:45:00', '15:25:00', '10th lesson'),
                                                                                        (NULL, 11, '15:30:00', '16:10:00', '11th lesson'),
                                                                                        (NULL, 12, '16:15:00', '16:55:00', '12th lesson'),
                                                                                        (NULL, 13, '17:00:00', '17:40:00', '13th lesson'),
                                                                                        (NULL, 14, '17:45:00', '18:25:00', '14th lesson');

-- =========================================================
-- ASSIGNMENTS FOR TIMETABLE 1 (FALL 2025-2026)
-- =========================================================

INSERT INTO assignments (timetable_id, subject_id, teacher_id, hours_per_week, shift, room_type_required, hours_splitting, generated_lessons_count, specific_room_id) VALUES
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 3, 15, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 8, 14, 2, 'ANY', 'CLASSROOM', '2', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 18, 6, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 19, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 20, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 22, 14, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 23, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 18, 6, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 19, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 20, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 23, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 18, 6, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 19, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 20, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 23, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 35, 8, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 35, 8, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 39, 19, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 35, 8, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 39, 19, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 35, 8, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 41, 5, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 42, 10, 12, 'ANY', 'ANY', '4+4+4', 0, NULL),
                                                                                                                                                                          (1, 43, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 44, 18, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 45, 13, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 41, 5, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 42, 10, 12, 'ANY', 'ANY', '4+4+4', 0, NULL),
                                                                                                                                                                          (1, 43, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 44, 18, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 45, 13, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 3, 15, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 23, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 40, 16, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 41, 5, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 43, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 1, 1, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 4, 2, 6, 'ANY', 'COMPUTER_LAB', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 5, 12, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 6, 12, 4, 'ANY', 'CLASSROOM', '2+2', 0, NULL),
                                                                                                                                                                          (1, 7, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 8, 14, 2, 'ANY', 'CLASSROOM', '2', 0, NULL),
                                                                                                                                                                          (1, 23, 17, 1, 'ANY', 'CLASSROOM', '1', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 34, 9, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 36, 18, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL),
                                                                                                                                                                          (1, 45, 13, 6, 'ANY', 'CLASSROOM', '2+2+2', 0, NULL);

-- =========================================================
-- ASSIGNMENT <-> GROUPS FOR TIMETABLE 1
-- =========================================================

INSERT INTO assignment_groups (assignment_id, group_id) VALUES(1, 1),
                                                              (2, 1),
                                                              (3, 1),
                                                              (4, 1),
                                                              (5, 1),
                                                              (6, 1),
                                                              (7, 1),
                                                              (8, 2),
                                                              (9, 2),
                                                              (10, 2),
                                                              (11, 2),
                                                              (12, 3),
                                                              (13, 3),
                                                              (14, 3),
                                                              (15, 3),
                                                              (16, 3),
                                                              (17, 4),
                                                              (18, 4),
                                                              (19, 4),
                                                              (20, 4),
                                                              (21, 4),
                                                              (22, 5),
                                                              (23, 5),
                                                              (24, 5),
                                                              (25, 5),
                                                              (26, 6),
                                                              (27, 6),
                                                              (28, 6),
                                                              (29, 6),
                                                              (30, 7),
                                                              (31, 7),
                                                              (32, 7),
                                                              (33, 8),
                                                              (34, 8),
                                                              (35, 8),
                                                              (36, 8),
                                                              (37, 9),
                                                              (38, 9),
                                                              (39, 9),
                                                              (40, 9),
                                                              (41, 10),
                                                              (42, 10),
                                                              (43, 10),
                                                              (44, 11),
                                                              (45, 11),
                                                              (46, 11),
                                                              (47, 11),
                                                              (48, 11),
                                                              (49, 12),
                                                              (50, 12),
                                                              (51, 12),
                                                              (52, 12),
                                                              (53, 12),
                                                              (54, 13),
                                                              (55, 13),
                                                              (56, 13),
                                                              (57, 13),
                                                              (58, 13),
                                                              (59, 13),
                                                              (60, 14),
                                                              (61, 14),
                                                              (62, 14),
                                                              (63, 14),
                                                              (64, 14),
                                                              (65, 15),
                                                              (66, 16),
                                                              (67, 17),
                                                              (68, 18),
                                                              (69, 19),
                                                              (70, 19),
                                                              (71, 19),
                                                              (72, 20),
                                                              (73, 20),
                                                              (74, 20),
                                                              (75, 20),
                                                              (76, 20),
                                                              (77, 21),
                                                              (78, 21),
                                                              (79, 21),
                                                              (80, 21),
                                                              (81, 21),
                                                              (82, 21),
                                                              (83, 22),
                                                              (84, 24),
                                                              (85, 25),
                                                              (86, 25),
                                                              (87, 25);

-- =========================================================
-- LUNCH
-- =========================================================
INSERT INTO lunch (timetable_id, group_id, day_of_week, start_time, end_time, is_manual) VALUES
                                                                                             (1, 1, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 1, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 1, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 1, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 1, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 1, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 2, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 3, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 4, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 5, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 6, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 7, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 8, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 9, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 10, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 11, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 12, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 13, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 14, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 15, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 16, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 17, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 18, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 19, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 20, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 21, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 22, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 24, 'SATURDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'MONDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'TUESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'WEDNESDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'THURSDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'FRIDAY', '12:30:00', '13:10:00', false),
                                                                                             (1, 25, 'SATURDAY', '12:30:00', '13:10:00', false);

-- =========================================================
-- USERS
-- =========================================================
INSERT INTO users (email, password, role) VALUES
                                              ('admin@university.kg', '$2a$08$a6r..ZYW.BK0UB0yJSwfc.30Alt2gSzmK/c0kkqLGqK7tIm9HVk/2', 'ADMIN'),
                                              ('scheduler@university.kg', '$2a$08$Iy5qn7TWG6LI.D2ATDvL5uPOftseKIhhWXUzyFHYnts1tFA1DNPNi', 'ADMIN');